# Generated by Django 3.1.7 on 2021-05-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('incomplete', 'incomplete'), ('failed', 'failed')], max_length=120),
        ),
    ]
